
- name: (Debian-like) Modify PAM SSHD, comment common-auth mechanism
  lineinfile:
    firstmatch: yes
    path: /etc/pam.d/sshd
    regexp: "^@include common-auth"
    line: "#@include common-auth"
    state: present

- name: (Debian-like) Insert the vault-ssh-helper configuration for ssh auth
  blockinfile:
    path: /etc/pam.d/sshd
    block: |
      auth requisite  pam_exec.so quiet expose_authtok log=/var/log/vault-ssh.log /usr/local/bin/vault-ssh-helper -dev -config=/etc/vault-ssh-helper.d/config.hcl
      auth optional pam_unix.so use_first_pass nodelay
    insertbefore: BOF
    state: present