- name: (RedHat-like) Modify PAM SSHD
  ansible.builtin.lineinfile:
    firstmatch: yes
    path: /etc/pam.d/sshd
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { regexp: '^auth       substack     password-auth', line: '#auth       substack     password-auth'}
    - { regexp: '^password       include     password-auth', line: '#password       include     password-auth'}

- name: (RedHat-like) Insert the vault-ssh-helper configuration for ssh auth
  ansible.builtin.blockinfile:
    path: /etc/pam.d/sshd
    block: |
      auth requisite  pam_exec.so quiet expose_authtok log=/var/log/vault-ssh.log /usr/local/bin/vault-ssh-helper -dev -config=/etc/vault-ssh-helper.d/config.hcl
      auth optional pam_unix.so use_first_pass nodelay
    insertbefore: "auth       include      postlogin"
    state: present