- name: Copia rotate_linux_password.sh
  copy:
    src: rotate_linux_password.sh
    dest: /etc/vault-ssh-helper.d
    owner: root
    group: root
    mode: '0700'

- name: Copia profile para adicionar as várivais do VAULT
  template:
    src: vault.sh
    dest: /etc/profile.d/vault.sh
    mode: '0700'
    owner: root
    group: root

- name: "Adiciona um trabalho no cron para rotacionar a senha local do usuário padrão"
  cron:
    name: "rotate local password for {{ item.user }}"
    minute: "{{ item.minute }}"
    hour: "{{ item.hour }}"
    user: "root"
    job: "BASH_ENV=/etc/profile /etc/vault-ssh-helper.d/rotate_linux_password.sh {{ item.user }}"
  with_items:
    - { user: "{{ default_linux_user }}", minute: '0', hour: '*/6' }
    - { user: "ansible", minute: '0', hour: '*/6' }

# - name: Realiza a chamada inicial do comando
#   command: "/etc/vault-ssh-helper.d/rotate_linux_password.sh {{ item }}"
#   with_items:
#     - "{{ default_linux_user }}"
#     - "ansible"