- name: Altera configurações no sshd_config
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^ChallengeResponseAuthentication', line: 'ChallengeResponseAuthentication yes'}
    - { regexp: '^UsePAM', line: 'UsePAM yes'}
    - { regexp: '^PasswordAuthentication', line: 'PasswordAuthentication no'}
  notify:
    - Restart sshd